services:
  patte-a-l-eau:
    build:
      context: .
      args:
        - NEXT_PUBLIC_BASE_URL=https://pattesaleau-toilettage.fr
    container_name: patte-a-l-eau
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - samy-network

networks:
  samy-network:
    external: true
    name: samy-repare_samy-network